### ISSUE TITLE
Empty output file

### ISSUE THREAD

**Issue by ognjen011** [enix/netbox-prometheus-sd#5]
Hi 
so i seem to be seeing an empty output file when i run the script. Is there a specific value that must be set for prom_labels that the script will check in netbox?

**Comment by NaPs** [comment]
Hi,

Yes, you have to fill this field with a list of settings for each exporter, expressed in JSON. For example, if you have the node exporter running, you can poll it with the following `prom_labels` value: `[{"__param_module": "node"}]`.

If you can read french, I wrote an how to use this tool on our blog: https://enix.io/fr/blog/service-discovery-avec-netbox-et-prometheus/.

Let me know if you need more help!

Antoine
